# Generated by Django 3.1.1 on 2021-04-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_category', models.CharField(default='', max_length=50)),
                ('sub_category', models.CharField(default='', max_length=50)),
                ('price', models.CharField(default='', max_length=10)),
                ('product_image', models.ImageField(default='', upload_to='')),
                ('product_des', models.CharField(max_length=250)),
                ('publish_date', models.DateField()),
            ],
        ),
    ]
