# Generated by Django 3.1.1 on 2021-05-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(default='0', max_length=15),
        ),
    ]
