# Generated by Django 3.1.1 on 2021-06-01 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0006_auto_20210601_1234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
    ]
